### ISSUE TITLE
Home Page Slider

### ISSUE THREAD

**Issue by danieltomasku** [danieltomasku/ok-studio-website-dynamic#20]
Port over the the Home Page slider JavaScript from static site to the new one.

**Comment by danieltomasku** [comment]
@antonlegoo i'm actually having trouble with this one. when i use `$refs` to count the amount of slides there are, it returns 0, even though 3 slides are created. i'm calling for the `$refs` in `mounted()`. i'm guessing that maybe the DOM elements don't exist when that is called but I can't figure out in which lifecycle method to try and access the `$refs`. Any advice?

**Comment by antonlegoo** [comment]
Are you using the carousel component or vue-flickity? 

If so, the ‘slides’ prop is actually a function and not an ‘int’ property. This got me. So you have to use it as:
‘let count = this.$refs.carousel.slides()’

**Comment by antonlegoo** [comment]
If not I can look at it when we meet up tomorrow
