### ISSUE TITLE
Bug: Video component doesn't re-render between projects

### ISSUE THREAD

**Issue by danieltomasku** [danieltomasku/ok-studio-website-dynamic#31]
Video component doesn't re-render when you navigate between project pages.

**Comment by danieltomasku** [comment]
What's the best Vue way to do this @antonlegoo ?

**Comment by antonlegoo** [comment]
@danieltomasku I was able to fix this at a higher level. I made some updates ([see here for details](http://michaelnthiessen.com/force-re-render/)) to ensure that **all** components aren't reused when switching between projects.

**Comment by danieltomasku** [comment]
@antonlegoo Interesting! So the Project component re-renders based on a key change. Nice 👌 Feel free to make a PR and merge it ✌️

**Comment by antonlegoo** [comment]
@danieltomasku yep, good stuff to know about 🌈 ⭐️ . I'll go ahead and merge
